# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablo', '0003_tabloproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabloproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='TabloProduct',
        ),
        migrations.DeleteModel(
            name='TabloProductImage',
        ),
    ]
