# Generated by Django 3.2 on 2022-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon_active',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
