# Generated by Django 3.2 on 2022-01-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcategory_icon_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='icon_active',
        ),
    ]
