# Generated by Django 3.2 on 2022-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220115_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
