# Generated by Django 3.2 on 2022-01-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20220115_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
    ]
