# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_evdekorproduct_evdekorproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusiveproducts', to='product.color')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusiveproducts', to='product.category')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusiveproducts', to='product.room')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusiveproducts', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Məhsullar - EXCLUSİVE ƏL İŞLƏRİ',
                'verbose_name_plural': 'Məhsullar - EXCLUSİVE ƏL İŞLƏRİ',
            },
        ),
        migrations.CreateModel(
            name='FotoOboyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotooboyproducts', to='product.color')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotooboyproducts', to='product.category')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotooboyproducts', to='product.room')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotooboyproducts', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Məhsullar - FOTOOBOY VE FRESKA',
                'verbose_name_plural': 'Məhsullar - FOTOOBOY VE FRESKA',
            },
        ),
        migrations.CreateModel(
            name='SelfTabloProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selftabloproducts', to='product.color')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selftabloproducts', to='product.category')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selftabloproducts', to='product.room')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selftabloproducts', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Məhsullar - ÖZ ŞƏKİLİNİZ İLƏ TABLO',
                'verbose_name_plural': 'Məhsullar - ÖZ ŞƏKİLİNİZ İLƏ TABLO',
            },
        ),
        migrations.CreateModel(
            name='SkinaliProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skinaliproducts', to='product.color')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skinaliproducts', to='product.category')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skinaliproducts', to='product.room')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skinaliproducts', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Məhsullar - SKİNALİ',
                'verbose_name_plural': 'Məhsullar - SKİNALİ',
            },
        ),
        migrations.CreateModel(
            name='TabloProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabloproducts', to='product.color')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabloproducts', to='product.category')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabloproducts', to='product.room')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabloproducts', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Məhsullar - TABLO VƏ ÇƏRÇİVƏLƏR',
                'verbose_name_plural': 'Məhsullar - TABLO VƏ ÇƏRÇİVƏLƏR',
            },
        ),
        migrations.AlterModelOptions(
            name='evdekorproduct',
            options={'verbose_name': 'Məhsullar - EV ÜÇÜN DEKOR', 'verbose_name_plural': 'Məhsullar - EV ÜÇÜN DEKOR'},
        ),
        migrations.CreateModel(
            name='TabloProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.tabloproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SkinaliProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.skinaliproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SelfTabloProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.selftabloproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FotoOboyProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.fotooboyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusiveProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.exclusiveproduct')),
            ],
        ),
    ]
