# Generated by Django 3.2 on 2022-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20220120_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('texture_image', models.FileField(upload_to='')),
                ('youtube_url', models.CharField(max_length=255)),
                ('material_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Materiallar - FOTOOBOY VE FRESKA',
                'verbose_name_plural': 'Materiallar - FOTOOBOY VE FRESKA',
            },
        ),
    ]
