# Generated by Django 3.2 on 2022-01-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20220124_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='idd',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='idd2',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
