# Generated by Django 3.2 on 2022-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20220124_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='idd',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='idd2',
            field=models.CharField(max_length=255),
        ),
    ]
