# Generated by Django 3.2 on 2022-01-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20220124_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='idd2',
            new_name='iddd',
        ),
    ]
