# Generated by Django 3.2 on 2022-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_idd2_material_iddd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
