# Generated by Django 3.2 on 2022-04-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20220410_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
