# Generated by Django 3.2 on 2022-04-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
