# Generated by Django 3.2 on 2022-06-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20220625_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusiveproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='selftabloproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='selftabloproduct',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='selftabloproduct',
            name='room',
        ),
        migrations.RemoveField(
            model_name='selftabloproduct',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='selftabloproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tabloproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tabloproduct',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='tabloproduct',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tabloproduct',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='tabloproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ExclusiveProduct',
        ),
        migrations.DeleteModel(
            name='ExclusiveProductImage',
        ),
        migrations.DeleteModel(
            name='SelfTabloProduct',
        ),
        migrations.DeleteModel(
            name='SelfTabloProductImage',
        ),
        migrations.DeleteModel(
            name='TabloProduct',
        ),
        migrations.DeleteModel(
            name='TabloProductImage',
        ),
    ]
