# Generated by Django 3.2 on 2022-01-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evdekor', '0003_evdekorproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evdekorproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='EvDekorProduct',
        ),
        migrations.DeleteModel(
            name='EvDekorProductImage',
        ),
    ]
