# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinali', '0003_skinaliproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinaliproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='SkinaliProduct',
        ),
        migrations.DeleteModel(
            name='SkinaliProductImage',
        ),
    ]
