# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotooboy', '0003_fotooboyproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotooboyproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='FotoOboyProduct',
        ),
        migrations.DeleteModel(
            name='FotoOboyProductImage',
        ),
    ]
