# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selftablo', '0003_selftabloproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selftabloproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='SelfTabloProduct',
        ),
        migrations.DeleteModel(
            name='SelfTabloProductImage',
        ),
    ]
