# Generated by Django 3.2 on 2022-06-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
    ]
