# Generated by Django 3.2 on 2022-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='main_image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
