# Generated by Django 3.2 on 2022-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('elaqe', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazılan Mesajlar',
                'verbose_name_plural': 'Yazılan Mesajlar',
            },
        ),
    ]
