# Generated by Django 3.2 on 2022-04-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
