# Generated by Django 3.2 on 2022-01-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0003_exclusiveproductimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusiveproductimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='ExclusiveProduct',
        ),
        migrations.DeleteModel(
            name='ExclusiveProductImage',
        ),
    ]
